# App configuration for Google Cloud Run
runtime: python311

# Environment variables for Cloud Run
env_variables:
  ENVIRONMENT: production
  DEBUG: false
  LOG_LEVEL: INFO
  ALGORITHM: HS256
  ACCESS_TOKEN_EXPIRE_MINUTES: 30

# Automatic scaling configuration
automatic_scaling:
  min_instances: 0
  max_instances: 10
  target_cpu_utilization: 0.6

# Resource allocation
resources:
  cpu: 1
  memory_gb: 1

# Health check configuration
liveness_check:
  path: "/health"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 1

readiness_check:
  path: "/health"
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 1
  app_start_timeout_sec: 300

# VPC connector (if needed for private resources)
# vpc_access_connector:
#   name: projects/PROJECT_ID/locations/REGION/connectors/CONNECTOR_NAME
