name: Deploy Azure Static Web Apps Frontend

on:
  push:
    branches: [ main ]
    paths: 
      - 'frontend/**'
  pull_request:
    branches: [ main ]
    paths: 
      - 'frontend/**'
  workflow_dispatch:

env:
  NODE_VERSION: '18.x'
  APP_LOCATION: './frontend'
  OUTPUT_LOCATION: 'dist'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        cache-dependency-path: '${{ env.APP_LOCATION }}/package-lock.json'

    - name: Install dependencies
      run: |
        cd ${{ env.APP_LOCATION }}
        npm ci

    - name: Build frontend
      run: |
        cd ${{ env.APP_LOCATION }}
        npm run build
      env:
        VITE_API_BASE_URL: https://sage-24293-api.azurewebsites.net/api
        VITE_APP_ENV: production

    - name: Deploy to Azure Static Web Apps
      uses: Azure/static-web-apps-deploy@v1
      with:
        azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        action: 'upload'
        app_location: ${{ env.APP_LOCATION }}
        output_location: ${{ env.OUTPUT_LOCATION }}
        skip_app_build: true