name: Deploy Azure Static Web Apps Frontend

on:
  push:
    branches: [main]
    paths:
      - 'frontend/**'
  pull_request:
    branches: [main]
    paths:
      - 'frontend/**'
  workflow_dispatch:

env:
  NODE_VERSION: '20.x'
  APP_LOCATION: './frontend' # Location of the source code
  OUTPUT_LOCATION: 'dist' # Name of the build output directory

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: '${{ env.APP_LOCATION }}/package-lock.json'

      - name: Install dependencies and Build
        run: |
          cd ${{ env.APP_LOCATION }}
          npm install
          npm run build
        env:
          VITE_API_BASE_URL: https://sage-24293-api.azurewebsites.net/api
          VITE_APP_ENV: production
          NODE_ENV: production

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: 'upload'

          # Point to the correct locations for deployment
          app_location: ${{ env.APP_LOCATION }}
          output_location: ${{ env.OUTPUT_LOCATION }}

          # Because we are building in a previous step, we tell the action to skip its own build.
          # The action will now correctly look inside the app_location for the output_location folder and deploy only that.
          skip_app_build: true
