name: Deploy Azure Functions Backend

on:
  push:
    branches: [main]
    paths:
      - 'server/**'
  pull_request:
    branches: [main]
    paths:
      - 'server/**'
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_NAME: sage-24293-api
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './server'
  PYTHON_VERSION: '3.11'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python version
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Create and start virtual environment
        run: |
          cd ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          python -m venv .venv
          source .venv/bin/activate

      - name: Install dependencies
        run: |
          cd ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          source .venv/bin/activate
          pip install --upgrade pip
          echo "Installing Python dependencies..."
          pip install -r requirements.txt --no-cache-dir
          echo "Dependencies installed successfully"

      - name: Zip artifact for deployment
        run: |
          cd ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          echo "Creating deployment package..."
          zip -r ../backend-deployment.zip function_app.py host.json requirements.txt app/ --exclude="*.pyc" "__pycache__/*" ".pytest_cache/*" "*.log" ".env*" "local.settings.json"
          echo "Deployment package created:"
          ls -lh ../backend-deployment.zip

      - name: List contents of deployment zip
        run: unzip -l backend-deployment.zip

      - name: Deploy to Azure Functions
        id: fa
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: './backend-deployment.zip'
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
          # The following flags force the remote build process on Azure
          scm-do-build-during-deployment: true
          enable-oryx-build: true

      - name: Test deployment
        run: |
          echo "Waiting 60 seconds for deployment to stabilize..."
          sleep 60
          echo "Pinging health check endpoint: ${{ steps.fa.outputs.app-url }}/health"
          curl -f "${{ steps.fa.outputs.app-url }}/health" || (echo "Health check failed" && exit 1)
