name: Deploy FastAPI Backend to Azure Functions

on:
  push:
    branches: [main]
    paths:
      - 'server/**'
  pull_request:
    branches: [main]
    paths:
      - 'server/**'
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_NAME: sage-24293-api
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './server'
  PYTHON_VERSION: '3.11'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python version
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          cd ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          python -m pip install --upgrade pip
          pip install -r requirements.txt --no-cache-dir

      - name: Zip artifact for deployment
        run: |
          cd ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          zip -r ../backend-deployment.zip . \
            --exclude="*.pyc" "__pycache__/*" ".pytest_cache/*" "*.log" ".env*" "local.settings.json" ".venv/*" "venv/*" "*.git*"

      - name: List contents of deployment zip
        run: unzip -l backend-deployment.zip

      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: './backend-deployment.zip'
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}

      - name: Test deployment
        run: |
          echo "Waiting 60 seconds for deployment to stabilize..."
          sleep 60
          BASE_URL="https://${{ env.AZURE_FUNCTIONAPP_NAME }}.azurewebsites.net"
          echo "Testing endpoints..."
          curl -v "$BASE_URL/health" || echo "Health endpoint failed"
          curl -v "$BASE_URL/docs" || echo "Docs endpoint failed"
          curl -v "$BASE_URL/api/v1/health" || echo "API v1 health failed"
